use aluguel

insert into Categorias (nmcategoria) values ('VideoGame')
insert into Categorias (nmcategoria) values ('AudioVisual')
insert into Categorias (nmcategoria) values ('Música & Hobbies')
insert into Categorias (nmcategoria) values ('Esporte & Ginástica')
insert into Categorias (nmcategoria) values ('Ferramentas')
insert into Categorias (nmcategoria) values ('Eletrodomésticos')

select*from Categorias

insert into Tipos (nmtipo, categoriaid) values ('Console','1')
insert into Tipos (nmtipo, categoriaid) values ('Jogos','1')
insert into Tipos (nmtipo, categoriaid) values('Acessórios','1')
insert into Tipos (nmtipo, categoriaid) values ('Outros','1')
insert into Tipos (nmtipo, categoriaid) values ('DVD Player & BluRay','2')
insert into Tipos (nmtipo, categoriaid) values ('Som Profissional','2')
insert into Tipos (nmtipo, categoriaid) values ('Projetores','2')
insert into Tipos (nmtipo, categoriaid) values ('Acessórios','2')
insert into Tipos (nmtipo, categoriaid) values ('Outros','2')
insert into Tipos (nmtipo, categoriaid) values ('Instrumentos Musicais','3')
insert into Tipos (nmtipo, categoriaid) values ('CDs, DVDs etc','3')
insert into Tipos (nmtipo, categoriaid) values ('Livros & Revistas','3')
insert into Tipos (nmtipo, categoriaid) values ('Hobbies & Coleções','3')
insert into Tipos (nmtipo, categoriaid) values ('Outros','3')
insert into Tipos (nmtipo, categoriaid) values ('Fitness & Luta','4')
insert into Tipos (nmtipo, categoriaid) values ('Futebol & Acessórios','4')
insert into Tipos (nmtipo, categoriaid) values ('Pranchas & Esp. Aquáticos','4')
insert into Tipos (nmtipo, categoriaid) values ('Skates & Patins','4')
insert into Tipos (nmtipo, categoriaid) values ('Ciclismo','4')
insert into Tipos (nmtipo, categoriaid) values ('Outros','4')
insert into Tipos (nmtipo, categoriaid) values ('Furadeira','5')
insert into Tipos (nmtipo, categoriaid) values ('Parafusadeira','5')
insert into Tipos (nmtipo, categoriaid) values ('Serras','5')
insert into Tipos (nmtipo, categoriaid) values ('Lixadeira','5')
insert into Tipos (nmtipo, categoriaid) values ('Chaves','5')
insert into Tipos (nmtipo, categoriaid) values ('Esmerilhadeira','5')
insert into Tipos (nmtipo, categoriaid) values ('Martelete','5')
insert into Tipos (nmtipo, categoriaid) values ('Micro Retífica','5')
insert into Tipos (nmtipo, categoriaid) values ('Ferramentas Manuais','5')
insert into Tipos (nmtipo, categoriaid) values ('Outros','5')
insert into Tipos (nmtipo, categoriaid) values ('Batedeira','6')
insert into Tipos (nmtipo, categoriaid) values ('Espremedor de Frutas','6')
insert into Tipos (nmtipo, categoriaid) values ('Fatiador','6')
insert into Tipos (nmtipo, categoriaid) values ('Moedor','6')
insert into Tipos (nmtipo, categoriaid) values ('Churrasqueira Elétrica','6')
insert into Tipos (nmtipo, categoriaid) values ('Chapinha','6')
insert into Tipos (nmtipo, categoriaid) values ('Secador de Cabelo','6')
insert into Tipos (nmtipo, categoriaid) values ('Cortador de Grama','6')
insert into Tipos (nmtipo, categoriaid) values ('Roçadeira','6')
insert into Tipos (nmtipo, categoriaid) values ('Soprador de Folhas','6')
insert into Tipos (nmtipo, categoriaid) values ('Tosquiadeira','6')
insert into Tipos (nmtipo, categoriaid) values ('Outros','6')

select*from Tipos